### ISSUE TITLE
'import-requirements' is broken

### ISSUE THREAD

**Issue by MikeClapper** [RedisGears/GearsCli#9]
his example command will demonstrate the problem:
python3 main.py import-requirements --requirements-path exports/redisgears-requirement-v1-pandas-linux-buster-x64.zip --host localhost --port 6399
This last lines of the output:
File "/Users/mikeclapper/.pyenv/versions/3.7.5/lib/python3.7/zipfile.py", line 1225, in init
self._RealGetContents()
File "/Users/mikeclapper/.pyenv/versions/3.7.5/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

The problem appears to be in the routine 'import_requirements' - line 254 - 'import_single_req()' is called using a buffer rather than a file name.

253 io_buffer = io.BytesIO(req_data)
245 import_single_req(r, io_buffer, bulk_size_in_bytes)

**Comment by AlexMikhalev** [comment]
I can confirm this bug:
export requirements work:
```
gears-cli export-requirements --host 127.0.0.1 --port 30001 --all --save-directory exports
```
import from the same folder doesn't:
```gears-cli import-requirements --host 127.0.0.1 --port 30001 --requirements-path ./exports/redisgears-requirement-v1-langdetect==1.0.8-.zip```

Error:
Warngin: no requirements specified
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/pattern_env/bin/gears-cli", line 8, in <module>
    sys.exit(main())
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 295, in main
    gears_cli()
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 276, in import_requirements
    install_req(req)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 254, in install_req
    import_single_req(r, io_buffer, bulk_size_in_bytes)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 224, in import_single_req
    with zipfile.ZipFile(req_io, "r", zipfile.ZIP_DEFLATED, False) as zf:
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by MeirShpilraien** [comment]
I am sorry for the late late late response, the --requirements-path should be a zip file or directory in which we will search for requirements (a zip file contains the requirement), it is also described in the help message:
```
--requirements-path TEXT  Path of requirements directory containing
                            requirements zip files, could also be a zip file
                            contains more requirements zip files
```                 
So if you put all the exported requirements in one zip file and do:
```
python3 main.py import-requirements --requirements-path my_requirements.zip --host localhost --port 6399 --all
```
It will import all the requirements at my_requirements.zip

**Comment by AlexMikhalev** [comment]
Tried above, but broken for me on export now:
```
gears-cli export-requirements --host 127.0.0.1 --port 30001 --all --save-directory exports
Saving exported requirement into /home/alex/py_code/the-pattern-platform/exports/redisgears-requirement-v1-pyahocorasick@master#egg=pyahocorasick-linux-buster-x64.zip
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/pattern_env/bin/gears-cli", line 8, in <module>
    sys.exit(main())
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 295, in main
    gears_cli()
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 200, in export_requirements
    export_single_req(r, md['Name'], save_directory, output_prefix)
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/site-packages/gears_cli/__main__.py", line 176, in export_single_req
    with zipfile.ZipFile(filePath, "a", zipfile.ZIP_DEFLATED, False) as zf:
  File "/home/alex/miniconda3/envs/pattern_env/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alex/py_code/the-pattern-platform/exports/redisgears-requirement-v1-pyahocorasick@master#egg=pyahocorasick-linux-buster-x64.zip'
```
Offending requirement:
```
cat requirements_gears_aho.txt 
httpimport
joblib
git+https://github.com/WojciechMula/pyahocorasick@master#egg=pyahocorasick
```
Export seems doesn't like #egg=pyahocorasick

**Comment by MeirShpilraien** [comment]
amm thanks @AlexMikhalev will check this out and report ASAP.
